### ISSUE TITLE
How to add 3rd level menu on meganav ?

### ISSUE THREAD

**Issue by priyabratary** [BST-Plus/BST-Plus#10]
can you please tell me how to add  3rd level menu on meganav ? like this screenshot ?
https://drive.google.com/file/d/0B3o6b7iUDDsHb25fOU5IREQtZEE/view?usp=sharing

and can you pleas tell me how can I place an image on meaga menu like follows ?
https://drive.google.com/file/d/0B3o6b7iUDDsHdjFtT3lIOXhoYU0/view?usp=sharing
https://drive.google.com/file/d/0B3o6b7iUDDsHWUpQd0lRZnUxdnM/view?usp=sharing

Thank you very much for your help.

**Comment by SimonPadbury** [comment]
Hello Priyabratary,

**Update:** Sorry I missed what you meant by "third level menu" – I thought you meant grandchild menu items. But you mean great-grandchild menu items. Sorry I only set up for grandchildren. I would urge you to reconsider whether you need to go so deep as great-grandchildren – that makes things very complicated for your visitors to understand. **End of update.**

Meganav is simple in concept – it only overrides some Bootstrap 3 styles (using some CSS and some jQuery to add meganav classes). I have no screenshot handy. To set it up, you only need to drag menu items a little further over, in the normal WordPress Menus builder. Imagine this is a screen shot of the WordPress Menus builder:

```
Parent 1
    Child 1.1
      Grandchild 1.1.1
      Grandchild 1.1.2
      Grandchild 1.1.3
    Child 1.2
      Grandchild 1.2.1
      Grandchild 1.2.2
      Grandchild 1.2.3
    Child 1.3
      Grandchild 1.3.1
      Grandchild 1.3.2
      Grandchild 1.3.3
Parent 2
.... etc.
```

**Note:** meganav will only appear if you have a grandchild (at least one). The meganav jQuery script looks for grandchildren menu items and, if it finds any, it will inject the special meganav classes into the navbar at that required place.

You have noticed that there are 4 optional positions for placing the menu:
- Upper navbar (left)
- Upper navbar (right)
- Lower navbar (left)
- Lower navbar (right)

When you have chosen and set up your mega menu(s), you can go into the theme `header.php` and delete any that you don't need.

If you require images within the menu, I can suggest two options, depending on how competent in writing CSS code is client (the person/company for whom you are making the website):
1. Delete all the meganav stuff in the CSS file and in the JS file for BST-Plus, and then find a mega-menu plugin. I found this one – it is free and good – it may give you everything you need: [http://demo.woorockets.com/plugins/wr-megamenu/](http://demo.woorockets.com/plugins/wr-megamenu/). Some others (free or paid) are listed here: [http://www.sourcewp.com/wordpress-mega-menu-plugins/](http://www.sourcewp.com/wordpress-mega-menu-plugins/).
2. If you continue with my meganav, I guess this will work:

### How to add images to meganav

(1.) When you have set up a menu with grandchildren, go to the frontend and inspect the HTML code, and copy the ID of the menu item where you require the image. Example:

```
<li id="menu-item-12345">
  <a href.......
  </a>
</li>
```

(2.) In your CSS, you can add the image as though it were a background, to the (first) `<a>` within the `<li>`. You will also need to improve the height and add some top padding to accommodate your image. Example:

```
#menu-item-12345 a:first-child {
    height: 100px;
    background: url('path/to/your/image.png') 0 0 no-repeat;
    background-size: 64px auto;
    padding-top: 72px
}
```

Hope this helps.

Kind regards,

Simon

**Comment by SimonPadbury** [comment]
**Update:** Sorry I missed what you meant by "third level menu" – I thought you meant grandchild menu items. But you mean great-grandchild menu items. Sorry I only set up for grandchildren. I would urge you to reconsider whether you need to go so deep as great-grandchildren – that makes things very complicated for your visitors to understand. **End of update.**

**Comment by priyabratary** [comment]
Sir, thank you very much for your replay, is there any way to add great-grandchild menu items as my client requiring this. Your help will be appreciate.
Thank you

**Comment by SimonPadbury** [comment]
Hello Priyabratary

Sorry I can't do this – I have tried various CSS, but I can't override make the 4th level menu to pop out of its `<li>` container, (but the `<li>` container has CSS `display: table-cell`). You require the 4th level `<ul>` to by (probably) `display: absolute` on a new layer above. I couldn't get this to work. 

The 4th level menu is selected, as follows:

```
ul.mega-menu ul ul ul { }
```

Maybe you could try this, to get further than I did. but first, you will need to inform WordPress that you require this 4th level menu. Do this by going to the theme `includes/header.php` and then finding the `.navbar-nav` (there are four of these). Choose the one that you require this modification for.

Therein, you need change the depth from 3 to 4, as follows:

```
             'depth'              => 4,
```

Please let me know how you get on.

Kind regards,

Simon
