### ISSUE TITLE
Duplicate class definition bug

### ISSUE THREAD

**Issue by DeepSilver** [BST-Plus/BST-Plus#3]
The css class on author span is duplicated in two places
https://github.com/BST-Plus/BST-Plus/blob/master/includes/loops/content.php#L22
https://github.com/BST-Plus/BST-Plus/blob/master/includes/loops/content-single.php#L16

should read
... span class="text-muted author">

**Comment by SimonPadbury** [comment]
Thanks, DeepSilver. These are now fixed.
