### ISSUE TITLE
e.preventDefault() not working

### ISSUE THREAD

**Issue by nicogaldo** [BST-Plus/BST-Plus#6]
I tried to make a smooth navigation for anchors, but do not know why not interpret the preventDefault.

In previous versions, this if it worked perfect.

**Comment by ghost** [comment]
Hi, try comment out this in bst-plus.js :-)

``` javascript
// Restore "clickable parent links" in navbar
$('.hovernav a').click(function () {
    window.location = this.href;
});
```

**Comment by SimonPadbury** [comment]
Hi Tomáš,
Thankyou. This was not working anyway.
And I just updated to Bootstrap 3.3.5

```
  From: Tomáš Frantík <notifications@github.com>
```

 To: BST-Plus/BST-Plus BST-Plus@noreply.github.com 
 Sent: Wednesday, 4 November 2015, 16:26
 Subject: Re: [BST-Plus] e.preventDefault() not working (#6)

Hi, try comment out this :-)
// Restore "clickable parent links" in navbar
$('.hovernav a').click(function () {
 window.location = this.href;
});—
