### ISSUE TITLE
Menu _blank open in current tab and new tab

### ISSUE THREAD

**Issue by nicogaldo** [BST-Plus/BST-Plus#7]
When I set the menus in the target = "_ blank" does not operate normally, as when clicking opens the link in a tab where I am positioned, and in a new tab.

**Comment by nicogaldo** [comment]
Thank you for your attention. I managed solved by removing these lines of code in js/bts-plus.js line 44

```
// Restore "clickable parent links" in navbar
$('.hovernav a').click(function () {
    window.location = this.href;
});
```

**Comment by SimonPadbury** [comment]
Hi Nico,
Sorry I didn't get around to responding to this. Vacation.
Simon
